spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: book-catalog-service
        uri: lb://BOOK-CATALOG-SERVICE
        predicates:
        - Path=/catalog/**
      - id: book-added-info-service
        uri: lb://BOOK-ADDED-INFO-SERVICE
        predicates:
        - Path=/bookinfo/**
eureka:
  instance:
    hostname: localhost
logging:
  file: logs\edge-gateway.log