spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
      - id: book-catalog-service
        uri: lb://BOOK-CATALOG-SERVICE
        predicates:
        - Path=/catalog/**
      - id: book-added-info-service
        uri: lb://BOOK-ADDED-INFO-SERVICE
        predicates:
        - Path=/bookinfo/**
logging:
  file: logs\edge-gateway.log