spring:
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9761/eureka/