eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
logging:
  level:
    blog.panditmandar.scdemo.bookdata: INFO
spring:
    boot:
        admin:
            client:
                url: http://localhost:8761