spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  datasource:
    url: jdbc:h2:mem:bookdb
    driverClassName: org.h2.Driver
    username: scdemo
    password: scdemopass
  jpa:
    deferDatasourceInitialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 20
  h2:
    console:
      enabled: true
      path: /h2-bookdb
      settings:
        trace: false
logging:
  file: logs\book-data-service.log