eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9761/eureka/
logging:
  level:
    blog.panditmandar.scdemo.bookdata: DEBUG
spring:
    boot:
        admin:
            client:
                url: '[http://localhost:9761]'