spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
ribbon:
  eureka:
    enabled: true
logging:
  file: logs\book-catalog-service.log